/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCompras;

import Clases.Productos;
import ControlCompras.Conexion;
import java.awt.BorderLayout;
import static VistaCompras.Compras.pnlPrincipalCompras;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUIS
 */
public class FrmDetallePedCompra extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarPedido
     */
    DefaultTableModel tablaProductos2;
    
    public FrmDetallePedCompra() {
        initComponents();
        
        FrmPedidoCompra pc=new FrmPedidoCompra();
        String cadena=pc.enviarCodigo();
        
        //txtNumPedido.setText(pc.enviarCodigo());
        String [] cabecera={"Codigo","Descripción", "Precio Unitario","Cantidad"};
        String [] cuerpo = new String[4];
           
        tablaProductos2=new DefaultTableModel(null,cabecera);
        //bloquearCasillas();
        //btnBuscar.setEnabled(true);
        //btnCrear.setEnabled(true);
        //btnVerTabla.setEnabled(true);
        
        Connection cn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        String sql="";
        
        try{
            cn = Conexion.getConexion();
            sql= "Select codProducto from producto";
            ps = cn.prepareStatement(sql);
            rs=ps.executeQuery();
            
            cboProductos2.addItem("Seleccione producto: ");

            while (rs.next()){
               
                cboProductos2.addItem(rs.getString("codProducto"));               
            }            
            rs.close();
        }catch(Exception e){
            e.printStackTrace();              
        }finally{
            try{
                if (rs!=null) rs.close();
                if (ps!=null) ps.close();
                if (cn!=null) cn.close();
            }catch(Exception e2){
                    e2.printStackTrace();                  
            }
        }
        //String codigo=(String)cboProductos2.getSelectedItem();
        /*try{
            cn = Conexion.getConexion();
            sql= "Select descripcion, precioUnitario from producto where codProducto=?";
            ps = cn.prepareStatement(sql);
            ps.setString(1,(String)cboProductos2.getSelectedItem());
            rs=ps.executeQuery();

            while (rs.next()){
              
                txtDescripciónProducto.setText(rs.getString("descripcion"));
                txtPrecioProducto.setText(rs.getString("precioUnitario"));
            }            
            rs.close();
        }catch(Exception e){
            e.printStackTrace();              
        }finally{
            try{
                if (rs!=null) rs.close();
                if (ps!=null) ps.close();
                if (cn!=null) cn.close();
            }catch(Exception e2){
                    e2.printStackTrace();                  
            }
        } */
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetallePedCompra = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        pnlNuevoPedido = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescripciónProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        cboProductos2 = new javax.swing.JComboBox<>();
        btnEscogerProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        tblDetallePedCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDetallePedCompra);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Detalle Pedido");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel4.setText("Producto:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Descripción:");

        jLabel7.setText("Precio:");

        txtDescripciónProducto.setEditable(false);
        txtDescripciónProducto.setText("Sin Descripción");

        txtPrecioProducto.setEditable(false);
        txtPrecioProducto.setText("Sin Precio");

        cboProductos2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProductos2ItemStateChanged(evt);
            }
        });
        cboProductos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboProductos2MouseClicked(evt);
            }
        });
        cboProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProductos2ActionPerformed(evt);
            }
        });

        btnEscogerProducto.setText("Escoger");
        btnEscogerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevoPedidoLayout = new javax.swing.GroupLayout(pnlNuevoPedido);
        pnlNuevoPedido.setLayout(pnlNuevoPedidoLayout);
        pnlNuevoPedidoLayout.setHorizontalGroup(
            pnlNuevoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuevoPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNuevoPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboProductos2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addGroup(pnlNuevoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlNuevoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevoPedidoLayout.createSequentialGroup()
                        .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEscogerProducto))
                    .addComponent(txtDescripciónProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlNuevoPedidoLayout.setVerticalGroup(
            pnlNuevoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNuevoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtDescripciónProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlNuevoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscogerProducto))
                .addGap(2, 2, 2))
        );

        jLabel1.setText("Num. Pedido:");

        txtNumPedido.setText("Sin datos");
        txtNumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPedidoActionPerformed(evt);
            }
        });

        btnVer.setText("Ver Orden");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnVer))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(pnlNuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer)
                    .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(pnlNuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnSalir))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         Fondo f=new Fondo();
         f.setSize(580,390);
         f.setLocation(5,5);
        
       pnlPrincipalCompras.removeAll();
       pnlPrincipalCompras.add(f, BorderLayout.CENTER);
       pnlPrincipalCompras.revalidate();
       pnlPrincipalCompras.repaint();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmPedidoCompra np = new FrmPedidoCompra();
       
        
        np.setSize (600,500);
        np.setLocation(5,5);
        
       pnlPrincipalCompras.removeAll();
       pnlPrincipalCompras.add(np, BorderLayout.CENTER);
       pnlPrincipalCompras.revalidate();
       pnlPrincipalCompras.repaint();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPedidoActionPerformed

    private void cboProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProductos2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboProductos2ActionPerformed

    private void cboProductos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboProductos2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cboProductos2MouseClicked

    private void cboProductos2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProductos2ItemStateChanged
        // TODO add your handling code here:
        int posicion=cboProductos2.getSelectedIndex();
        String codigo=(String)cboProductos2.getSelectedItem();
        if (posicion>0){
            Connection cn = null;
            PreparedStatement ps = null;
            ResultSet rs = null;        
            String sql="";
            try{
                cn = Conexion.getConexion();
                sql= "Select descripcion, precioUnitario from producto where codProducto=?";
                ps = cn.prepareStatement(sql);
                ps.setString(1,(String)cboProductos2.getSelectedItem());
                rs=ps.executeQuery();

                while (rs.next()){
              
                    txtDescripciónProducto.setText(rs.getString("descripcion"));
                    txtPrecioProducto.setText(rs.getString("precioUnitario"));
                }            
                rs.close();
            }catch(Exception e){
                e.printStackTrace();              
            }finally{
                try{
                    if (rs!=null) rs.close();
                    if (ps!=null) ps.close();
                    if (cn!=null) cn.close();
                }catch(Exception e2){
                    e2.printStackTrace();                  
                }
            }   
        }
    }//GEN-LAST:event_cboProductos2ItemStateChanged

    private void btnEscogerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerProductoActionPerformed
        // TODO add your handling code here:
        
        if (cboProductos2.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Debe escoger un producto");
        }else{
            String [] cabecera={"Codigo","Descripción", "Precio Unitario","Cantidad"};
            tablaProductos2=new DefaultTableModel(null,cabecera);
            
            String [] cuerpo = new String[4];  
            cuerpo[0]=(String)cboProductos2.getSelectedItem();
            cuerpo[1]=txtDescripciónProducto.getText();
            cuerpo[2]=txtPrecioProducto.getText();
            cuerpo[3]=txtCantidad.getText();
 
            tablaProductos2.addRow(cuerpo);
            tblDetallePedCompra.setModel(tablaProductos2);
          
        } 
    }//GEN-LAST:event_btnEscogerProductoActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        //bloquearCasillas();
        //activarCasillas();
        //btnCancelar.setEnabled(true);

        String[] cabecera = {"Orden", "Producto", "Cantidad",};
        String[] cuerpo = new String[3];

        tablaProductos2 = new DefaultTableModel(null, cabecera);

        Connection cn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "Select * from detalle_pedido_compra where codPedido_Compra = ? ";
        try {
            cn = Conexion.getConexion();
            ps = cn.prepareStatement(sql);
            ps.setString(1, txtNumPedido.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Registro encontrado");
                cuerpo[0] = rs.getString("codPedido_Compra");
                cuerpo[1] = rs.getString("codProducto");
                cuerpo[2] = rs.getString("cantidad");
                
                tablaProductos2.addRow(cuerpo);

                tblDetallePedCompra.setModel(tablaProductos2);
                txtNumPedido.setText("");;
            } else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado");
                //txtCodigoProv.setText("");
                btnVer.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);

            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnVerActionPerformed
    public void obtenerCodigo(String codped){
    txtNumPedido.setText(codped);
    
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscogerProducto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cboProductos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlNuevoPedido;
    private javax.swing.JTable tblDetallePedCompra;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripciónProducto;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
