/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCompras;

import Clases.Proveedor;
import ControlCompras.Conexion;
import ControlCompras.ControlProveedor;
import java.awt.BorderLayout;
import static VistaCompras.Compras.pnlPrincipalCompras;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUIS
 */
public class FrmProveedor extends javax.swing.JPanel {

    /**
     * Creates new form CrearProveedor
     */
    DefaultTableModel tablaProveedor;

    public FrmProveedor() {
        initComponents();

        String[] cabecera = {"Codigo", "Razón Social", "Dirección", "Teléfono", "Email", "Ruc", "Estado"};
        String[] cuerpo = new String[7];

        tablaProveedor = new DefaultTableModel(null, cabecera);
        bloquearCasillas();
        btnBuscar.setEnabled(true);
        btnCrear.setEnabled(true);
        btnVerTabla.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        btnVerTabla = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtOpcion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoProv = new javax.swing.JTextField();
        txtRazonSocialProv = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        txtDireccionProv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefonoProv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRucProv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailProv = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(616, 360));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 0, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Proveedor");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedor);
        tblProveedor.getAccessibleContext().setAccessibleName("");

        btnVerTabla.setText("Ver Todos");
        btnVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTablaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel1.setText("Código:");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel5.setText("Razón Social:");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel9.setText("Dirección:");

        txtCodigoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProvActionPerformed(evt);
            }
        });

        txtRazonSocialProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialProvActionPerformed(evt);
            }
        });

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        txtDireccionProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionProvActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel10.setText("Teléfono:");

        txtTelefonoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoProvActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel6.setText("RUC:");

        txtRucProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucProvActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel7.setText("Email:");

        txtEmailProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccionProv, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodigoProv, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnVer))
                            .addComponent(txtRazonSocialProv, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEmailProv, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTelefonoProv, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRucProv, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRazonSocialProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelefonoProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtRucProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(246, 246, 246)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVerTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)))
                        .addComponent(txtOpcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnGrabar)
                        .addGap(75, 75, 75)
                        .addComponent(btnCancelar)
                        .addGap(96, 96, 96)
                        .addComponent(btnSalir)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(txtOpcion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVerTabla)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrabar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:
        
        Proveedor prov = new Proveedor();
        prov.setPcodigo(txtCodigoProv.getText());
        prov.setPnombre(txtRazonSocialProv.getText());
        prov.setPruc(txtRucProv.getText());
        prov.setPdireccion(txtDireccionProv.getText());
        prov.setPtelefono(txtTelefonoProv.getText());
        prov.setPemail(txtEmailProv.getText());
        prov.setPestado("ACTIVO");
        prov.setOpcion(Integer.parseInt(txtOpcion.getText()));
        int r=validar();
        switch (r){ 
            case 0:
                ControlProveedor cprov = new ControlProveedor();
                cprov.mantProv(prov);
                limpiar();
                mostrarTabla();
                bloquearCasillas();
                btnVerTabla.setEnabled(true);
                btnCrear.setEnabled(true);
                btnBuscar.setEnabled(true);
                txtOpcion.setText("0");
                break;
            case 1: JOptionPane.showMessageDialog(null, "Campos vacios");break;
            case 2: JOptionPane.showMessageDialog(null, "Ruc Inválido");break;
            case 3: JOptionPane.showMessageDialog(null, "Código inválido");break;
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Fondo f = new Fondo();
        f.setSize(600, 500);
        f.setLocation(5, 5);

        pnlPrincipalCompras.removeAll();
        pnlPrincipalCompras.add(f, BorderLayout.CENTER);
        pnlPrincipalCompras.revalidate();
        pnlPrincipalCompras.repaint();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtRazonSocialProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialProvActionPerformed
        // TODO add your handling code here:
        txtRazonSocialProv.transferFocus();
    }//GEN-LAST:event_txtRazonSocialProvActionPerformed

    private void txtCodigoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProvActionPerformed
        // TODO add your handling code here:
        txtCodigoProv.transferFocus();
    }//GEN-LAST:event_txtCodigoProvActionPerformed

    private void txtRucProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucProvActionPerformed
        // TODO add your handling code here:
        txtRucProv.transferFocus();
    }//GEN-LAST:event_txtRucProvActionPerformed

    private void txtDireccionProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionProvActionPerformed
        // TODO add your handling code here:
        txtDireccionProv.transferFocus();
    }//GEN-LAST:event_txtDireccionProvActionPerformed

    private void txtTelefonoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoProvActionPerformed
        // TODO add your handling code here:
        txtTelefonoProv.transferFocus();
    }//GEN-LAST:event_txtTelefonoProvActionPerformed

    private void txtEmailProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailProvActionPerformed
        // TODO add your handling code here:
        txtEmailProv.transferFocus();
    }//GEN-LAST:event_txtEmailProvActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        bloquearCasillas();
        activarCasillas();
        btnCancelar.setEnabled(true);

        String[] cabecera = {"Codigo", "Razón Social", "Dirección", "Teléfono", "Email", "Ruc", "Estado"};
        String[] cuerpo = new String[7];

        tablaProveedor = new DefaultTableModel(null, cabecera);

        Connection cn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "Select * from proveedor where cod_proveedor = ? ";
        try {
            cn = Conexion.getConexion();
            ps = cn.prepareStatement(sql);
            ps.setString(1, txtCodigoProv.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Registro encontrado");
                cuerpo[0] = rs.getString("cod_proveedor");
                cuerpo[1] = rs.getString("razonSocial");
                cuerpo[2] = rs.getString("dir_Proveedor");
                cuerpo[3] = rs.getString("telProveedor");
                cuerpo[4] = rs.getString("emailProveedor");
                cuerpo[5] = rs.getString("ruc");
                cuerpo[6] = rs.getString("estadoProv");
                tablaProveedor.addRow(cuerpo);

                tblProveedor.setModel(tablaProveedor);
                txtCodigoProv.setText("");;
            } else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado");
                txtCodigoProv.setText("");
                btnVer.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);

            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }


    }//GEN-LAST:event_btnVerActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        bloquearCasillas();
        activarCasillas();
        limpiar();
        btnCancelar.setEnabled(true);
        btnGrabar.setEnabled(true);
        txtOpcion.setText("1");
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTablaActionPerformed
        // TODO add your handling code here:
        bloquearCasillas();
        limpiar();
        mostrarTabla();
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnVerTablaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        txtOpcion.setText("2");
        bloquearCasillas();
        txtRazonSocialProv.setEnabled(true);
        txtDireccionProv.setEnabled(true);
        txtEmailProv.setEnabled(true);
        txtTelefonoProv.setEnabled(true);
        txtRucProv.setEnabled(true);
        btnGrabar.setEnabled(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        // TODO add your handling code here:
        try {
            int fila = tblProveedor.getSelectedRow();
            String codigo = tblProveedor.getValueAt(fila, 0).toString();
            Connection cn = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            cn = Conexion.getConexion();
            String sql = "Select cod_proveedor,razonSocial,dir_Proveedor,telProveedor,"
                    + "emailProveedor,ruc from proveedor where cod_proveedor =?";
            ps = cn.prepareStatement(sql);
            ps.setString(1, codigo);
            rs = ps.executeQuery();

            while (rs.next()) {
                txtCodigoProv.setText(String.valueOf(codigo));
                txtRazonSocialProv.setText(rs.getString("razonSocial"));
                txtDireccionProv.setText(rs.getString("dir_Proveedor"));
                txtTelefonoProv.setText(rs.getString("telProveedor"));
                txtEmailProv.setText(rs.getString("emailProveedor"));
                txtRucProv.setText(rs.getString("ruc"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        bloquearCasillas();
        txtCodigoProv.setEnabled(false);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_tblProveedorMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int rspta = -1;
        bloquearCasillas();
        rspta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro?");
        if (rspta == 0) {
            txtOpcion.setText("3");
            Proveedor prov = new Proveedor();
            prov.setPcodigo(txtCodigoProv.getText());
            prov.setOpcion(Integer.parseInt(txtOpcion.getText()));
            ControlProveedor cprov = new ControlProveedor();
            cprov.mantProv(prov);
        } else {
            JOptionPane.showMessageDialog(null, "Registro no fue eliminado");
        }

        mostrarTabla();
        btnCrear.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnVerTabla.setEnabled(true);
        txtOpcion.setText("0");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquearCasillas();
        btnVer.setEnabled(true);
        txtCodigoProv.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        bloquearCasillas();
        limpiar();

        btnBuscar.setEnabled(true);
        btnCrear.setEnabled(true);
        btnVerTabla.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed
    void limpiar() {

        txtCodigoProv.setText("");
        txtRazonSocialProv.setText("");
        txtDireccionProv.setText("");
        txtTelefonoProv.setText("");
        txtEmailProv.setText("");
        txtRucProv.setText("");
        //String [] cuerpo = new String[7];     
        //tablaProveedor.addRow(cuerpo);              
        tblProveedor.setModel(tablaProveedor);
    }

    void bloquearCasillas() {
        txtCodigoProv.setEnabled(false);
        txtRazonSocialProv.setEnabled(false);
        txtDireccionProv.setEnabled(false);
        txtEmailProv.setEnabled(false);
        txtTelefonoProv.setEnabled(false);
        txtRucProv.setEnabled(false);
        btnGrabar.setEnabled(false);
        btnVer.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnVerTabla.setEnabled(false);
        btnCrear.setEnabled(false);

    }

    void activarCasillas() {
        txtCodigoProv.setEnabled(true);
        txtRazonSocialProv.setEnabled(true);
        txtDireccionProv.setEnabled(true);
        txtEmailProv.setEnabled(true);
        txtTelefonoProv.setEnabled(true);
        txtRucProv.setEnabled(true);

    }

    void mostrarTabla() {

        String[] cabecera = {"Codigo", "Razón Social", "Dirección", "Teléfono", "Email", "Ruc", "Estado"};
        String[] cuerpo = new String[7];

        tablaProveedor = new DefaultTableModel(null, cabecera);
        try {
            Connection cn = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            String sql = "Select * from proveedor";
            cn = Conexion.getConexion();
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                cuerpo[0] = rs.getString("cod_proveedor");
                cuerpo[1] = rs.getString("razonSocial");
                cuerpo[2] = rs.getString("dir_Proveedor");
                cuerpo[3] = rs.getString("telProveedor");
                cuerpo[4] = rs.getString("emailProveedor");
                cuerpo[5] = rs.getString("ruc");
                cuerpo[6] = rs.getString("estadoProv");
                tablaProveedor.addRow(cuerpo);
            }
            tblProveedor.setModel(tablaProveedor);
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int validar() {
        int resultado = 0;
        
        if (txtRucProv.getText().length()<11 || txtRucProv.getText().length()>11 ){
            resultado = 2;}
        if (txtCodigoProv.getText().length()<8 || txtCodigoProv.getText().length()>8 ){
            resultado = 3;
        }
        if (txtCodigoProv.getText().equals("")  || txtCodigoProv.getText() == null||
            txtRazonSocialProv.getText().equals("")  || txtRazonSocialProv.getText() == null||
            txtDireccionProv.getText().equals("")  || txtDireccionProv.getText() == null||
            txtEmailProv.getText().equals("")  || txtEmailProv.getText() == null||
            txtRucProv.getText().equals("")  || txtRucProv.getText() == null||
            txtTelefonoProv.getText().equals("")  || txtTelefonoProv.getText() == null) {
            resultado = 1;
        }
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVerTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtCodigoProv;
    private javax.swing.JTextField txtDireccionProv;
    private javax.swing.JTextField txtEmailProv;
    private javax.swing.JLabel txtOpcion;
    private javax.swing.JTextField txtRazonSocialProv;
    private javax.swing.JTextField txtRucProv;
    private javax.swing.JTextField txtTelefonoProv;
    // End of variables declaration//GEN-END:variables
}
