/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCompras;

import Clases.Productos;
import ControlCompras.Conexion;
import ControlCompras.ControlProductos;
import java.awt.BorderLayout;
import static VistaCompras.Compras.pnlPrincipalCompras;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUIS
 */
public class FrmProducto extends javax.swing.JPanel {

    /**
     * Creates new form CrearProducto
     */
    DefaultTableModel tablaProducto;

    public FrmProducto() {
        initComponents();
        String[] cabecera = {"Codigo", "Descripción", "Precio Unitario", "Stock Mínimo", "Area Producto", "Proveedor"};
        String[] cuerpo = new String[6];

        tablaProducto = new DefaultTableModel(null, cabecera);
        //bloquearCasillas();
        btnBuscar.setEnabled(true);
        btnCrear.setEnabled(true);
        btnVerTabla.setEnabled(true);

        Connection cn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        String sql = "";

        try {
            cn = Conexion.getConexion();
            sql = "Select * from area_producto";
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();

            cboArea.addItem("Seleccione área: ");

            while (rs.next()) {

                cboArea.addItem(rs.getString("nombreAreaProducto"));
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        try {
            cn = Conexion.getConexion();
            sql = "Select * from proveedor";
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            cboProveedor.addItem("Seleccione proveedor: ");
            while (rs.next()) {
                cboProveedor.addItem(rs.getString("razonSocial"));
            }
            rs.close();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtStockMin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboArea = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboProveedor = new javax.swing.JComboBox<>();
        btnIr = new javax.swing.JButton();
        txtOpcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnVerTabla = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Producto");

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Código:");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Descripción:");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Precio:");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("Stock Mínimo:");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Área:");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Proveedor:");

        cboProveedor.setToolTipText("");

        btnIr.setText("Ir");
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnIr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtOpcion))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addComponent(cboProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(btnIr))
                    .addComponent(txtOpcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVerTabla.setText("Ver Todos");
        btnVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTablaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnGrabar)
                        .addGap(39, 39, 39)
                        .addComponent(btnCancelar)
                        .addGap(52, 52, 52)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar)
                            .addComponent(btnVerTabla)
                            .addComponent(btnCrear)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Fondo f = new Fondo();
        f.setSize(580, 390);
        f.setLocation(5, 5);

        pnlPrincipalCompras.removeAll();
        pnlPrincipalCompras.add(f, BorderLayout.CENTER);
        pnlPrincipalCompras.revalidate();
        pnlPrincipalCompras.repaint();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:

        Productos prod = new Productos();
        prod.setCodigo(txtCodigo.getText());
        prod.setDescripcion(txtDescripcion.getText());
        prod.setPrecioUnitario(Double.parseDouble(txtPrecio.getText()));
        prod.setStockMinimo(Integer.parseInt(txtStockMin.getText()));
        prod.setArea((String) cboArea.getSelectedItem());
        prod.setProveedor((String) cboProveedor.getSelectedItem());
        //prod.setPestado("ACTIVO");
        prod.setOpcion(Integer.parseInt(txtOpcion.getText()));
        JOptionPane.showMessageDialog(null, prod.getPrecioUnitario());
        JOptionPane.showMessageDialog(null, prod.getStockMinimo());
        int r = validar2();
        switch (r) {
            
            case 0:
                ControlProductos cprod = new ControlProductos();
                cprod.MantProd(prod);
                limpiar();
                mostrarTabla();
                bloquearCasillas();
                btnVerTabla.setEnabled(true);
                btnCrear.setEnabled(true);
                btnBuscar.setEnabled(true);
                txtOpcion.setText("0");
                break;
            case 1: JOptionPane.showMessageDialog(null, "Campos vacios");break;
            case 2: JOptionPane.showMessageDialog(null, "Código inválido");break;   
        }

    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTablaActionPerformed
        // TODO add your handling code here:
        mostrarTabla();

    }//GEN-LAST:event_btnVerTablaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        bloquearCasillas();
        activarCasillas();
        limpiar();
        btnCancelar.setEnabled(true);
        btnGrabar.setEnabled(true);
        txtOpcion.setText("1");
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquearCasillas();
        btnIr.setEnabled(true);
        txtCodigo.setEnabled(true);
        btnCancelar.setEnabled(true);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        // TODO add your handling code here:
        bloquearCasillas();
        activarCasillas();
        btnCancelar.setEnabled(true);

        String[] cabecera = {"Codigo", "Descripción", "Precio Unitario", "Stock Mínimo", "Area Producto", "Proveedor"};
        String[] cuerpo = new String[6];

        tablaProducto = new DefaultTableModel(null, cabecera);

        Connection cn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String sql = "select x.codProducto,x.descripcion,x.precioUnitario,x.stockMin,p.razonSocial,ap.nombreAreaProducto from producto x "
                + "inner join proveedor p on x.cod_proveedor=p.cod_proveedor "
                + "inner join area_producto ap on x.cod_Area_Producto=ap.cod_Area_Producto where codProducto=?";
        try {
            cn = Conexion.getConexion();
            ps = cn.prepareStatement(sql);
            ps.setString(1, txtCodigo.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Registro encontrado");
                cuerpo[0] = rs.getString("codProducto");
                cuerpo[1] = rs.getString("descripcion");
                cuerpo[2] = rs.getString("precioUnitario");
                cuerpo[3] = rs.getString("stockMin");
                cuerpo[4] = rs.getString("nombreAreaProducto");
                cuerpo[5] = rs.getString("razonSocial");
                //cuerpo[6]=rs.getString("estadoProv"); 
                tablaProducto.addRow(cuerpo);

                tblProducto.setModel(tablaProducto);
                txtCodigo.setText("");;

            } else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado");
                txtCodigo.setText("");
                btnIr.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);

            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }


    }//GEN-LAST:event_btnIrActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        txtOpcion.setText("2");
        bloquearCasillas();
        txtDescripcion.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtStockMin.setEnabled(true);
        cboArea.setEnabled(true);
        cboProveedor.setEnabled(true);
        btnGrabar.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        // TODO add your handling code here:
        try {
            int fila = tblProducto.getSelectedRow();
            String codigo = tblProducto.getValueAt(fila, 0).toString();
            Connection cn = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            cn = Conexion.getConexion();
            String sql = "select x.codProducto,x.descripcion,x.precioUnitario,x.stockMin,p.razonSocial,ap.nombreAreaProducto from producto x "
                    + "inner join proveedor p on x.cod_proveedor=p.cod_proveedor "
                    + "inner join area_producto ap on x.cod_Area_Producto=ap.cod_Area_Producto where codProducto=?";
            ps = cn.prepareStatement(sql);
            ps.setString(1, codigo);
            rs = ps.executeQuery();

            while (rs.next()) {
                txtCodigo.setText(String.valueOf(codigo));
                txtDescripcion.setText(rs.getString("descripcion"));
                txtPrecio.setText(rs.getString("precioUnitario"));
                txtStockMin.setText(rs.getString("stockMin"));
                cboArea.setSelectedItem(rs.getString("nombreAreaProducto"));
                cboProveedor.setSelectedItem(rs.getString("razonSocial"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        bloquearCasillas();
        txtCodigo.setEnabled(false);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_tblProductoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int rspta = -1;
        bloquearCasillas();
        rspta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro?");
        if (rspta == 0) {
            txtOpcion.setText("3");
            Productos producto = new Productos();
            producto.setCodigo(txtCodigo.getText());
            producto.setOpcion(Integer.parseInt(txtOpcion.getText()));
            ControlProductos mxp = new ControlProductos();
            mxp.MantProd(producto);
        } else {
            JOptionPane.showMessageDialog(null, "Registro no fue eliminado");
        }

        mostrarTabla();
        btnCrear.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnVerTabla.setEnabled(true);
        txtOpcion.setText("0");

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        bloquearCasillas();
        limpiar();

        btnBuscar.setEnabled(true);
        btnCrear.setEnabled(true);
        btnVerTabla.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed
    void mostrarTabla() {

        String[] cabecera = {"Codigo", "Descripción", "Precio Unitario", "Stock Mínimo", "Area Producto", "Proveedor"};
        String[] cuerpo = new String[6];

        tablaProducto = new DefaultTableModel(null, cabecera);
        try {
            Connection cn = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            String sql = "select x.codProducto,x.descripcion,x.precioUnitario,x.stockMin stock,p.razonSocial,ap.nombreAreaProducto from producto x "
                    + "inner join proveedor p on x.cod_proveedor=p.cod_proveedor "
                    + "inner join area_producto ap on x.cod_Area_Producto=ap.cod_Area_Producto";
            cn = Conexion.getConexion();
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                cuerpo[0] = rs.getString("codProducto");
                cuerpo[1] = rs.getString("descripcion");
                cuerpo[2] = rs.getString("precioUnitario");
                cuerpo[3] = rs.getString("stock");
                cuerpo[4] = rs.getString("nombreAreaProducto");
                cuerpo[5] = rs.getString("razonSocial");
                //cuerpo[6]=rs.getString("estadoProv"); 
                tablaProducto.addRow(cuerpo);
            }
            tblProducto.setModel(tablaProducto);
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void bloquearCasillas() {
        txtCodigo.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtStockMin.setEnabled(false);
        cboArea.setEnabled(false);
        cboProveedor.setEnabled(false);
        btnGrabar.setEnabled(false);
        btnIr.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnVerTabla.setEnabled(false);
        btnCrear.setEnabled(false);

    }

    void activarCasillas() {
        txtCodigo.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtStockMin.setEnabled(true);
        cboArea.setEnabled(true);
        cboProveedor.setEnabled(true);
    }

    void limpiar() {

        txtCodigo.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtStockMin.setText("");
        cboArea.setSelectedIndex(0);
        cboProveedor.setSelectedIndex(0);
        //String [] cuerpo = new String[7];     
        //tablaProveedor.addRow(cuerpo);              
        tblProducto.setModel(tablaProducto);
    }

    public int validar2() {
        int resultado = 0;
        
        if (txtCodigo.getText().equals("") || txtCodigo.getText() == null
                || txtDescripcion.getText().equals("") || txtDescripcion.getText() == null
                || txtPrecio.getText().equals("") || txtPrecio.getText() == null
                || txtStockMin.getText().equals("") || txtStockMin.getText() == null
                || cboArea.getSelectedIndex() == 0 || cboProveedor.getSelectedIndex() == 0) {
            resultado = 1;
        }
        if (txtCodigo.getText().length() < 8 || txtCodigo.getText().length() > 8) {
            resultado = 2;
        }
     
        return resultado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnIr;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerTabla;
    private javax.swing.JComboBox<String> cboArea;
    private javax.swing.JComboBox<String> cboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JLabel txtOpcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStockMin;
    // End of variables declaration//GEN-END:variables
}
