
package VistaCompras;

import Clases.Usuario;
import ControlCompras.Conexion;
import ControlCompras.ControlUsuario;
import java.awt.Color;
import java.net.URL;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //        setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorDimension2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorDimension2D();
        jPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        txtPass = new jtextfieldround.JPasswordFieldRound();
        btnAcceder = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblOpciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setBackground(new java.awt.Color(0, 0, 0,0));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LoginFala.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 410));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario :");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 80, -1));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar_verde_login.png"))); // NOI18N
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar login.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 35, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Sistema De Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 200, -1));

        txtUsuario.setToolTipText("");
        txtUsuario.setName(""); // NOI18N
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 220, 30));

        lblContraseña.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblContraseña.setText("Password :");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 100, -1));

        lblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Administrador.png"))); // NOI18N
        jPanel1.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 130, 130));

        txtPass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 220, -1));

        btnAcceder.setForeground(new java.awt.Color(0, 153, 153));
        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 90, 30));

        jCheckBox1.setForeground(new java.awt.Color(0, 153, 153));
        jCheckBox1.setText("Recordar contraseña");
        jCheckBox1.setBorderPainted(true);
        jCheckBox1.setBorderPaintedFlat(true);
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        lblOpciones.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 220, 20));

        jPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 740, 370));

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        /*String resultado="";
        //Conexion  c = new Conexion();
        //c.conector(); 
        Usuario user=new Usuario();
        user.setXemail(txtUsuario.getText());
        user.setXpassword(txtPass.getText());
        
        ControlUsuario controlus= new ControlUsuario();
        resultado= controlus.Autenticacion(user);
        */
        String resultado1="HOLA";
        //resultado1=muestraNombre();
        
        if (resultado1!=null){
             JOptionPane.showMessageDialog(null, "Bienvenido "+ resultado1);
            Menu m=new Menu();
            m.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Fallaste" );
        }
       /* if (Perfiles1.equals("Administrador") && Usuario.equals("Luis") && Pass.equals("123")) {
           JOptionPane.showMessageDialog(null, "Bienvenido");
           Menu m=new Menu();
           m.setVisible(true);
           this.dispose();
//            lblOpciones(Color.BLUE);
        } else if (Perfiles1.equals("Jefe De Almacen") &&Usuario.equals("Kirby") && Pass.equals("12345")) {
     
            JOptionPane.showMessageDialog(null, "Bienvenido");
           Menu m=new Menu();
           m.setVisible(true);
           this.dispose();
        } else {
            lblOpciones.setText("Usuario Y/O Passwor Incorrectos");
        }*/
    }//GEN-LAST:event_btnAccederActionPerformed
    public String muestraNombre(){
        String resultado="";
        Usuario user=new Usuario();
        user.setXemail(txtUsuario.getText());
        user.setXpassword(txtPass.getText());
        
        ControlUsuario controlus= new ControlUsuario();
        resultado= controlus.Autenticacion(user);
        return resultado;
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnCerrar;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorDimension2D evaluatorDimension2D1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblUsuario;
    private jtextfieldround.JPasswordFieldRound txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
